version: "3.9"

services:
  ref-staging-server:
    container_name: ref-staging-server
    image: ${APP_IMAGE_STG_SERVER}:${APP_IMAGE_STG_SERVER_TAG}
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      MODE: ${MODE}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
      MICROSOFT_TENANT_ID: ${MICROSOFT_TENANT_ID}
      MICROSOFT_CLIENT_SECRET_ID: ${MICROSOFT_CLIENT_SECRET_ID}
      PUBLIC_URL: ${PUBLIC_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      ref-staging-postgres:
        condition: service_healthy
      ref-staging-redis:
        condition: service_started
    networks:
      - refina_staging_network
    restart: always

  ref-staging-client:
    container_name: ref-staging-client
    image: ${APP_IMAGE_STG_CLIENT}:${APP_IMAGE_STG_CLIENT_TAG}
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - ref-staging-server
    networks:
      - refina_staging_network
    restart: always

  ref-staging-postgres:
    container_name: ref-staging-postgres
    image: postgres:17.5-alpine
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - refina_staging_network
    restart: always

  ref-staging-redis:
    container_name: ref-staging-redis
    image: redis:7.2-alpine
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    networks:
      - refina_staging_network
    restart: always

volumes:
  staging_postgres_data:

networks:
  refina_staging_network:
    name: refina_staging_network
    driver: bridge