# ! This Docker Compose file sets up a pgAdmin, RedisInsight, and Portainer.
# ! for local, development, staging and production environment.

services:
  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ideamint.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - local_network
      - refina_network # Refina network for production
      - refina_staging_network # Refina staging network
    restart: always
  redis_insights:
    container_name: redis_insights
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsights_data:/data
    networks:
      - local_network
      - refina_network # Refina network for production
      - refina_staging_network # Refina staging network
    restart: always
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - local_network
      - refina_network # Refina network for production
      - refina_staging_network # Refina staging network
    restart: always

volumes:
  pgadmin_data:
  portainer_data:
  redisinsights_data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/redis_insights
      o: bind