services:
  # server:
  #   container_name: server
  #   build: ./server
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./server/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - server
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: refina
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backup-160625.sql:/docker-entrypoint-initdb.d/backup-160625.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
