services:
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  client:
    container_name: client
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: refina
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data:
