FROM golang:1.22.4 AS builder

WORKDIR /app
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest
RUN apk add --no-cache postgresql-client

WORKDIR /app
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY db/migrations/ ./migrations/

COPY migrate.sh ./migrate.sh
RUN chmod +x migrate.sh

CMD ["./migrate.sh"]