FROM golang:1.22.4 AS builder

WORKDIR /app

COPY go.mod ./ 
COPY go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main cmd/api/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder app/main .
COPY config.json .
EXPOSE 8080

CMD ["./main"]